### ISSUE TITLE
仪表盘的钻石数量无法显示个位数的“8”

### ISSUE THREAD

**Issue by VirtualTowel** [Zuosizhu/AzurLaneAutoScript#38]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了 Wiki 中的 常见问题(FAQ)
- [X] 我正在使用最新版的 Alas

### 描述你的问题

比如我现在的钻石数量是1048，但是仪表盘显示的是104
目前两台设备，截图方式分别是ADB_nc以及uiautomator2，均存在此问题
不知道是仪表盘版本的bug还是原版Alas已存在的问题？

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by Zuosizhu** [comment]
是原版也有的问题，代码完全复制lme的钻石识别
